# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
#theme: jekyll-theme-so-simple
#remote_theme: mmistakes/so-simple-theme@3.2.0
skin: "/assets/css/skins/kbdataservices.css"
locale: en-US

title: "KB Dataservices"
description: "dataservices of the KB, the national library of the Netherlands"
url: "https://kbnldataservices.github.io/kbnldataservices.github.io-staging" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl: "/"


blogtitle: "KB Dataservices News - STAGING"
blogdescription: "TEST SITE for News & updates about the dataservices of the KB, the national library of the Netherlands."
blogbaseurl: "/blog"

logo: "/images/logo-kb-zwart-transparant.png"
date_format: "%-d %b %Y"
#read_time: true
#words_per_minute: 130

google_fonts:
  - name: "Roboto-Slab"
    weights: "400,400i,700,700i"
  - name: "Lato"
    weights: "400,400i,700,700i"
   
google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
disqus:
  shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: KBdataservices # site's Twitter username, e.g. "mmistakes"

#copyright: "KBNL Dataservices, all texts released under <a href='https://creativecommons.org/licenses/by-sa/4.0/deed.en" rel="nofollow">CC-BY-SA 4.0</a> license."

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /blog/:title/
#

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

mathjax:
  enable: true # MathJax equations, e.g. true, false (default)

feed:
  path: atom.xml

# Pagination - https://jekyllrb.com/docs/pagination/
#paginate: 20
#paginate_path: /page:num/

# Search
search_full_content: true # can have performance implications for large sites

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-redirect-from


include:
  - _pages

# Taxonomy pages
category_archive_path: "/categories-grid/#"
tag_archive_path: "/tags-grid/#"

# Collections
collections:
  pinned:
    output: true
    permalink: /blog/:collection/:path/

# Front Matter Defaults
defaults:
  # Posts defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      share: true
      permalink: /blog/posts/:path/
  # Pinned defaults
  - scope:
      path: "_pinned"
      type: pinned
    values:
      layout: post
      comments: true
      share: true
    # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
      author_profile: false


# Site Author
author:
  name: KB Dataservices
  picture: /images/logo-zwart.png
  email: dataservices@kb.nl
  twitter: https://twitter.com/KBdataservices
  links:
    - title: Twitter
      url: https://twitter.com/KBdataservices
      icon: fab fa-twitter-square
    - title: Github
      url: https://github.com/KBNLdataservices
      icon: fab fa-github-square

